### ISSUE TITLE
Save the marking points

### ISSUE THREAD

**Issue by chokkarapu** [Teoge/MarkToolForParkingLotPoint#1]
Hello teogo,

Thanks for providing the tool for researchers.
hen I tried to use tool, after i Mark the points i got .mat file and then used mat2json scrip to convert .
I even got the .json file...

But the .json file which u provided in DMPR paper dataset-json file, has 
[x1,y1,x2,y2,0/1] as marks, but when i generated i got only [x1,y1] as marks.

Could u kindly provide how to generate the .json file format of yours.
I look forward for prompt reply.

Thanks,
Anil.

**Comment by Teoge** [comment]
Hello, Anil.

This repository has two branches, [`master`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/master) branch and [`directional_point`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/directional_point) branch.

The [`master`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/master) branch is intended for the labeling in the method "DeepPS", published in the paper "Vision-based Parking-slot Detection: A DCNN-based Approach and A Large-scale Benchmark Dataset"

And the [`directional_point`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/directional_point) branch is used for the labeling in "DMPR-PS".

This is because labeling in "DMPR-PS" is different from the labeling in "DeepPS". "DMPR-PS" requires more label information, which is the direction of each marking-point.

If you want to prepare your own dataset for "DMPR-PS", you need to use [`directional_point`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/directional_point) branch to label your images.

One more thing is that the `README.md` at [`directional_point`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/directional_point) branch is out-of-date. But you could easily figure out how to use it. It's similar to [`master`](https://github.com/Teoge/MarkToolForParkingLotPoint/tree/master) branch. I'll update the `README.md` in the future.

**Comment by chokkarapu** [comment]
@Teoge  : Thanks for your prompt reply....And giving more information...I will try to use use directional_point branch .
Will understand ur data set preparation by spending efficient time, i will revert back for any clarification.

Thanks,
Anil.

**Comment by chokkarapu** [comment]
Hi Teoge,

I have cloned @directional_point branch. Understood to maximum. 
My understating are follows,
1) For T-Shaped, the direction is towards inside slot, as shown below,
![t_Shaped](https://user-images.githubusercontent.com/3630515/68579944-4dcddb00-049b-11ea-97d1-016747733c6e.JPG)

Im totally confused with direction when marking as L_Shaped,
For below image u have taken direction as follow,
![L_Shaped_Right](https://user-images.githubusercontent.com/3630515/68580025-81106a00-049b-11ea-928d-829f19ccb753.JPG)

Where as for other image (L_Shaped) u have taken direction as shown below:
![image](https://user-images.githubusercontent.com/3630515/68580149-c5036f00-049b-11ea-84a8-0826f7fe6412.png)
Whereas for other image(L-Shaped), u considered following direction as shown below:
![image](https://user-images.githubusercontent.com/3630515/68580247-f845fe00-049b-11ea-8a59-e7b3f112d614.png)


So im totally confused with this set of labeling...
I request you to provide some details in takeing direction for L-Shaped especially...

I eagerly look forward for your response....

Thanks,
Anil.

**Comment by Teoge** [comment]
The definition of orientations of L-shaped marking-points is presented in our paper [DMPR-PS: A Novel Approach for Parking-Slot Detection Using Directional Marking-Point Regression](https://doi.org/10.1109/ICME.2019.00045).

In short, we define the orientation of a L-shaped marking-point as the direction along the marking-line that overlaps with the other marking-line after 90◦ clockwise rotation.

Following figure might help you understand the definition.

![l-shaped_illustration](https://user-images.githubusercontent.com/10808856/68642742-166a3780-054a-11ea-83ad-156f52fc8417.png)

**Comment by chokkarapu** [comment]
Thank U Teogo for making more clear understanding.

I have following two qeuries, kindly provide some information:
1) Have you ever tried with Open Slot type of Parking Slot as shown below,
![image](https://user-images.githubusercontent.com/3630515/68645786-19abf600-053f-11ea-8943-3ba25a91c065.png)

2) If I want to add one more type as Open shape, i.e. i will add 2 as point shape along with 0-T shaped and 1-LShaped, with addition of one more new shape your base code will work or need to modify any particular place of your code...

Thanks for your valuable tie.

Thanks,
Anil.

**Comment by Teoge** [comment]
Hello, Anil.

1. For your first question, the short answer is no. We collected our data in China, where parking-slots of open slot type are rarely seen. Thus we don't have enough samples to perform related experiments.
2. For your second question, if the "code" you mentioned is the code of this labeling tool, then yes, basically the code will work, as long as you add the shape correctly (which includes modifications of data structure, UI that sets marking-point type, and the corresponding UI callback function).
If the "code" you mentioned is the code of [DMPR-PS](https://github.com/Teoge/DMPR-PS), then the answer is no. Except for adding a new type, you'll need to modify the logic of marking-point pairing and lots of related stuff, in order to make it work on open slot type parking-slot detection.
